name: CI
on: [workflow_dispatch]
jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
    - name: Publish to PSGallery
      env:
        APIKEY: ${{ secrets.APIKEY }}
      run: .\publish.ps1
      shell: pwsh

