name: CI
on: [workflow_dispatch]
jobs:
  test:
    name: Build and Publish
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Test and Publish
      shell: pwsh
      env:
        APIKEY: ${{ secrets.APIKEY }}
      run: |
        ./build.ps1 -Bootstrap -Verbose
        ./Publish.ps1

